spring:
  profiles:
    active: development
  main:
    banner-mode: off

default-setting:
  defaultRate: 20.0
  applicationId: 1
prescoring-constants:
  minRequestedAmount: 10000.0
  minTerm: 6
  minAge: 18
scoring-constants:
  loanToSalaryRatio: 20.0
  minAge: 20
  maxAge: 60
  minWorkExperienceTotal: 12
  minWorkExperienceCurrent: 3
